# Generated by Django 4.0.3 on 2022-03-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='kilometraje',
            field=models.IntegerField(),
        ),
    ]
